# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, '8.4'

target 'iTunesRemote' do
	pod 'Valet'
end

target 'iTunesRemoteTests' do

end

target 'iTunesRemoteUITests' do

end

target 'iTunesRemote WatchKit App' do

end

target 'iTunesRemote WatchKit Extension' do

end

target 'iTunesRemote WatchKit 1 Extension' do

end

target 'iTunesRemote WatchKit 1 App' do

end

